### ISSUE TITLE
Scalability X-Axis

### ISSUE THREAD

**Issue by herrBez** [herrBez/ethereum-scalability#10]

**Comment by herrBez** [comment]
If we solve the two TODOs (one of them is related to #25  ) we can consider this issue done.

**Comment by herrBez** [comment]
How can we fix this typographical error: 

![screenshot_20180826_093756](https://user-images.githubusercontent.com/6976484/44625924-b7ec7580-a913-11e8-96b6-696f29a867d2.png)

I mean the nginx without capital letter after the period?

**Comment by herrBez** [comment]
![screenshot_20180826_171229](https://user-images.githubusercontent.com/6976484/44629685-37e60000-a953-11e8-90e3-7567bce665e7.png)

1) In the second sentence is "The Ethereum Implementation" or simply "Ethereum"?

2) The sentence from "Although" to "perspective" sounds strange. E.g., I cannot understand what the word "this" is referring to.

3) Maybe it is sufficient to cite 2 or 3 client implementation

**Comment by gfornari** [comment]
I think nginx not capital is not a mistake.

1. "The Ethereum Implementation", because the Ethereum specification (the yellow paper) doesn't specify anything about the network, right?
2. "this" refers to the different implementations. I wanted to point out that there is no functional distinction between the clients, making possibile a discussion agnostic about the implementation treating each node equally
3. Ok, I don't mind
